add edit and delete parks ~:-)
taken-for-granite/park-reviews pull request #9
Opened 2018-07-30 15:45 UTC by AndrewMcLellan

Added edit and delete methods to parks

2018-07-30 18:06 UTC, dpickett requested changes
great stuff here. this is coming along nicely. I've left some requested changes above. Please review and let me know if you have any questions.

2018-07-30 18:06 UTC, dpickett commented on app/controllers/api/v1/parks_controller.rb
> +        render json: {park: park, error: ''}
this does not provide the user with errors. If the error key is not going to be used, I recommend we just omit it. Also I recommend we include a `status: 422` here if validation fails

2018-07-30 18:06 UTC, dpickett commented on app/controllers/api/v1/reviews_controller.rb
> +    review = Review.find()
I think this will cause an error

2018-07-30 18:06 UTC, dpickett commented on app/controllers/parks_controller.rb
> +  protect_from_forgery unless: -> { request.format.json? }
is this an API controller? If not, this line is unnecessary.

2018-07-30 18:06 UTC, dpickett commented on app/controllers/parks_controller.rb
> +    puts "DID WE GET HERE!?"
this should be omitted in a PR

2018-07-30 18:06 UTC, dpickett commented on app/controllers/parks_controller.rb
> +    redirect_to "/parks/1"
do we want to perform this redirect to the same park every time?

2018-07-30 18:06 UTC, dpickett commented on app/controllers/parks_controller.rb
> +    @park.destroy
can everyone destroy a park? We may want to add some authorization logic here

2018-07-30 18:06 UTC, dpickett commented on app/javascript/react/containers/ParkFormContainer.js
> +        fetch(`/api/v1/parks.json`, {
because there is no interpolation here, the backticks are unnecessary

2018-07-30 18:06 UTC, dpickett commented on app/javascript/react/containers/ParkFormEditContainer.js
> +        this.setState({parkName: event.target.value})
tabs should be set to 2 spaces, soft tabs. I think this is indented one time too many

2018-07-30 18:06 UTC, dpickett commented on app/javascript/react/containers/ParkFormEditContainer.js
> +        this.setState({
the indentation here is one time too many as well.

2018-07-30 18:06 UTC, dpickett commented on app/javascript/react/containers/ParkFormEditContainer.js
> +        event.preventDefault();
the indentation here is one time too many as well.

2018-07-30 18:06 UTC, dpickett commented on app/javascript/react/containers/ParkFormEditContainer.js
> +            this.setState({ updatedPark: body.park, error: body.errors })
what happens if the update fails?

2018-07-30 18:06 UTC, dpickett commented on app/javascript/react/containers/ParkFormEditContainer.js
> +          this.setState({
if it's easier. I recommend just maintaining a `park` object in state. that way you can do things like

```javascript
this.setState({park: body.park})
```

2018-07-30 19:24 UTC, dpickett requested changes

2018-07-30 19:24 UTC, dpickett commented on app/controllers/api/v1/parks_controller.rb
> +        render json: {park: park, error: 'Update not Completed status: 422'}
`render json: {errors: park.errors}, status: 422`

2018-07-30 19:24 UTC, dpickett commented on app/javascript/react/containers/ParkFormEditContainer.js
> +            if (body.park != {}) {
let's be explicit about equality with the `!==` operation.

`body.park !== {}`

2018-07-31 18:23 UTC, bkincart commented on app/controllers/api/v1/reviews_controller.rb
> +
Please remove commented code prior to merge

2018-07-31 18:23 UTC, bkincart commented on app/javascript/react/containers/ParkFormEditContainer.js
> +        this.setState({
Follow up here

2018-07-31 18:23 UTC, merged